src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Objective__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Objective</label>
        <referenceTo>Objective__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Brand__c.object
<CustomObject>
    <fields>
        <fullName>Brand_Type__c</fullName>
        <label>Brand Type</label>
        <picklist>
            <picklistValues>
                <fullName>Generic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Classification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Group / Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brand</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brand Variant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual Variant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Configuration &amp; Container</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Innovation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Innovation</label>
        <type>Checkbox</type>
    </fields>
    <label>Brand</label>
    <nameField>
        <label>Brand Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ObjectiveTriggerActionsTest.cls
@isTest
private class ObjectiveTriggerActionsTest {

	static testMethod void testInsert() {
		
		Account account = Test_Helper.testInsertAccount('testAcct');
        
        Brand__c brand = new Brand__c();
        brand.Name = 'testBrand';
        brand.Innovation__c = true;
        // Start : Changing for US682/TA1267 - CC9/30: Note #2 - By Siddharth
        brand.Brand_Type__c = 'Individual Variant';
        // End : Changing for US682/TA1267 - CC9/30: Note #2 - By Siddharth
        insert brand;
        
        Bottle_Size__c bottleSize = new Bottle_Size__c();
        bottleSize.Name = '1000' ;
        insert bottleSize;
        
        BrandBottle_Size__c bbs = new BrandBottle_Size__c();
        bbs.Bottle_Size__c = bottleSize.Id;
        bbs.Brand__c = brand.Id;
        insert bbs;
		
		
		Objective__c objective = new Objective__c();
		//objective.Name = 'test123';
		objective.BrandBottle_Size__c = bbs.Id ;
		
		system.Test.startTest();
			insert objective ;
		system.Test.stopTest();		
		
	}
}