src/objects/Attribute__c.object
<CustomObject>
    <description>An Object that stores all the Attribute Types(Color,Flavor,Type) and its associated Attribute Values(Blue,Banana,Cocktails) along with its associated Atribute Value&apos;s Images(Fireworks Image for 4th of July)</description>
    <fields>
        <fullName>Attribute_Type__c</fullName>
        <description>A Picklist Field that contains all the Attribute types that are being seen on a Recipe</description>
        <label>Attribute Type</label>
        <picklist>
            <picklistValues>
                <fullName>Barware Needed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Color</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Description/Overview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drink Classification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drink Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Effort Level</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flavor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food Pairings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glassware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Good For Gatherings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Language</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Luxury Flag</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nutrition Fact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recipe Story</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Servings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serving Size</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Serving Style</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard Average Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tasting Notes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine Taste</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wine Type</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PublishedAsset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UnitofAlcohol</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Meta Description</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Page Title</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Page URL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEO Hints</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Dynamic__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A check box that helps in determining the Value of certain Attribute Types.</description>
        <label>Dynamic</label>
        <type>Checkbox</type>
    </fields>
    <label>Attribute</label>
    <nameField>
        <displayFormat>ATTR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Recipe__c.object
<CustomObject>
    <fields>
        <fullName>Recipe_Title__c</fullName>
        <label>Recipe Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Recipe</label>
    <nameField>
        <displayFormat>RCP-{0}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recipes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestBatchToDeleteRecipeAttribute.cls
@isTest 
private class TestBatchToDeleteRecipeAttribute {
	static void createData(){
		Recipe__c recipe = new Recipe__c();
		recipe.Recipe_Title__c = 'rt';
		insert recipe;
		Attribute__c attr = new Attribute__c();
		attr.Attribute_Type__c = 'Description/Overview';
		attr.Dynamic__c = true;
		insert attr;
		Recipe_Attribute__c rt = new Recipe_Attribute__c();
		rt.Attribute__c = attr.Id;
		rt.Recipe__c = recipe.Id;
		insert rt;
		Recipe_Attribute__c rt2 = new Recipe_Attribute__c();
		rt2.Attribute__c = attr.Id;
		rt2.Recipe__c = recipe.Id;
		insert rt2;
		
	}
    static testMethod void testMethod_TestBatchToDeleteRecipeAttribute() {
    	createData();
    	String query = 'select Id,Recipe_Title__c from Recipe__c limit 100';
    	Id btachId = Database.executeBatch(new BatchToDeleteRecipeAttribute(query));
    	
    }
}