src/objects/Attribute__c.object
<CustomObject>
    <description>An Object that stores all the Attribute Types(Color,Flavor,Type) and its associated Attribute Values(Blue,Banana,Cocktails) along with its associated Atribute Value&apos;s Images(Fireworks Image for 4th of July)</description>
    <fields>
        <fullName>API_External_ID__c</fullName>
        <displayFormat>A-{0000}</displayFormat>
        <externalId>true</externalId>
        <label>API External ID</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Dynamic__c</fullName>
        <defaultValue>false</defaultValue>
        <description>A check box that helps in determining the Value of certain Attribute Types.</description>
        <label>Dynamic</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Locale__c</fullName>
        <label>Locale</label>
        <picklist>
            <picklistValues>
                <fullName>EN-US</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>EN-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR-CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PT-BR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-MX</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-CL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ES-AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-GB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EN-IN</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Attribute</label>
    <nameField>
        <displayFormat>ATTR-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/APPIRIO_WebServiceCallRecpClasifDtl_Test.cls
/********************************************************************************************************************
Name        : APPIRIO_WebServiceCallRecpClasifDtl_Test
Updated By  : Appirio Offshore(Rishi Khirbat)   
Date        : 15th Jan, 2013
Purpose     : Test Class for 
				- APPIRIO_WebServiceCallRecipeClasifDtl
********************************************************************************************************************/
@isTest
private class APPIRIO_WebServiceCallRecpClasifDtl_Test {
	
	//variable declaration
	static Attribute__c attr;
	static Attribute__c attr1;
	static Attribute__c attr2;
	static Attribute__c attr3;
	static Attribute__c attr4;
	static Attribute__c attr5;
	static Attribute__c attr6;
	static Attribute__c attr7;
	static Attribute__c attr8;
	static Attribute__c attr9;
	static Attribute__c attr10;
	
	static {
		//Creating a bunch of Attribute Records
		attr = TestUtil.createAttribute('Color','TestBlue',null);
		attr1= TestUtil.createAttribute('Language','TestEnglish',null);
		attr2 = TestUtil.createAttribute('Flavor','TestStrawberry',null);
		attr3 = TestUtil.createAttribute('Drink Type','TestCocktails',null);
		attr4 = TestUtil.createAttribute('Glassware','TestGlassware',null);
        attr5 = TestUtil.createAttribute('Effort Level','TestEffortLevel',null);
        attr6 = TestUtil.createAttribute('Serving Style','TestServingStyle',null);
        attr7 = TestUtil.createAttribute('Wine Type','TestWineType',null);
        attr8 = TestUtil.createAttribute('Wine Taste','TestWineTaste',null);
        attr9 = TestUtil.createAttribute('Barware Needed','TestBarwareNeeded',null);
        attr10 = TestUtil.createAttribute('Test Drink Classification','TestDrinkClassification',null);
        attr10.Dynamic__c = true;
        update attr10;
	}
	
	//Test Web Service Call for Recipe Classifications
    static testMethod void WebServiceCallRecipeClasifictinsTest() {
    	String xmlString;
    	attr = [Select API_External_ID__c, Locale__c From Attribute__c Where Id=:attr.id];
    	
    	Test.startTest();
	    	// set up the request object
	        System.RestContext.request = new RestRequest();
	        RestContext.request.requestURI = '/CallRecipeClassificationDetails/';
	        
	        // Invoke the method directly
	        xmlString = APPIRIO_WebServiceCallRecipeClasifDtl.WebServiceCallRecipeClassificationDetails();
			System.assert(xmlString.contains('<?xml version="1.0"?>'));
	        System.assert(xmlString.contains('<recipeClassifications>'));
	        System.assert(xmlString.contains('<key>Color</key>'));
	        System.assert(xmlString.contains('<value id="'+attr.API_External_ID__c+'" Locale="'+attr.Locale__c+'">TestBlue</value>'));
	        System.assert(!xmlString.contains('<recipeClassification>Test Drink Classification'));
	        System.assert(xmlString.contains('<key>Occasion</key>'));
	        System.assert(xmlString.contains('<key>Brand</key>'));
	        System.assert(xmlString.contains('<key>Product</key>'));
	        System.assert(xmlString.contains('</recipeClassifications>'));
	        
	        // Invoke the method directly
	        RestContext.request.addParameter('Key', 'Color');
	        xmlString = APPIRIO_WebServiceCallRecipeClasifDtl.WebServiceCallRecipeClassificationDetails();
			System.assert(xmlString.contains('<?xml version="1.0"?>'));
	        System.assert(xmlString.contains('<recipeClassifications>'));
	        System.assert(xmlString.contains('<key>Color</key>'));
	        System.assert(xmlString.contains('<value id="'+attr.API_External_ID__c+'" Locale="'+attr.Locale__c+'">TestBlue</value>'));
	        System.assert(!xmlString.contains('<recipeClassification>Test Drink Classification'));
	        System.assert(!xmlString.contains('<key>Occasion</key>'));
	        System.assert(!xmlString.contains('<key>Brand</key>'));
	        System.assert(!xmlString.contains('<key>Product</key>'));
	        System.assert(xmlString.contains('</recipeClassifications>'));
	        
	        // Invoke the method directly
	        RestContext.request.addParameter('Key', 'Brand');
	        xmlString = APPIRIO_WebServiceCallRecipeClasifDtl.WebServiceCallRecipeClassificationDetails();
			System.assert(xmlString.contains('<?xml version="1.0"?>'));
	        System.assert(xmlString.contains('<recipeClassifications>'));
	        System.assert(!xmlString.contains('<key>Color</key>'));
	        System.assert(!xmlString.contains('<value id="'+attr.API_External_ID__c+'" Locale="'+attr.Locale__c+'">TestBlue</value>'));
	        System.assert(!xmlString.contains('<recipeClassification>Test Drink Classification'));
	        System.assert(!xmlString.contains('<key>Occasion</key>'));
	        System.assert(xmlString.contains('<key>Brand</key>'));
	        System.assert(!xmlString.contains('<key>Product</key>'));
	        System.assert(xmlString.contains('</recipeClassifications>'));
	        
	        // Invoke the method directly
	        RestContext.request.addParameter('Key', 'Product');
	        xmlString = APPIRIO_WebServiceCallRecipeClasifDtl.WebServiceCallRecipeClassificationDetails();
			System.assert(xmlString.contains('<?xml version="1.0"?>'));
	        System.assert(xmlString.contains('<recipeClassifications>'));
	        System.assert(!xmlString.contains('<key>Color</key>'));
	        System.assert(!xmlString.contains('<value id="'+attr.API_External_ID__c+'" Locale="'+attr.Locale__c+'">TestBlue</value>'));
	        System.assert(!xmlString.contains('<recipeClassification>Test Drink Classification'));
	        System.assert(!xmlString.contains('<key>Occasion</key>'));
	        System.assert(!xmlString.contains('<key>Brand</key>'));
	        System.assert(xmlString.contains('<key>Product</key>'));
	        System.assert(xmlString.contains('</recipeClassifications>'));
	        
	        // Invoke the method directly
	        RestContext.request.addParameter('Key', 'Occasion');
	        xmlString = APPIRIO_WebServiceCallRecipeClasifDtl.WebServiceCallRecipeClassificationDetails();
			System.assert(xmlString.contains('<?xml version="1.0"?>'));
	        System.assert(xmlString.contains('<recipeClassifications>'));
	        System.assert(!xmlString.contains('<key>Color</key>'));
	        System.assert(!xmlString.contains('<value id="'+attr.API_External_ID__c+'" Locale="'+attr.Locale__c+'">TestBlue</value>'));
	        System.assert(!xmlString.contains('<recipeClassification>Test Drink Classification'));
	        System.assert(xmlString.contains('<key>Occasion</key>'));
	        System.assert(!xmlString.contains('<key>Brand</key>'));
	        System.assert(!xmlString.contains('<key>Product</key>'));
	        System.assert(xmlString.contains('</recipeClassifications>'));
        Test.stopTest();
    }
}